const fields = {
  vccNo: "VCC No",
  vccStatus: "VCC Status",
  vccDate: "VCC Generation Date",
  chassisNo: "Chassis No",
  engineNumber: "Engine Number",
  yearBuilt: "Year Built",
  vehicleDrive: "Vehicle Drive",
  origin: "Country of Origin",
  engineCapacity: "Engine Capacity",
  carriageCapacity: "Carriage Capacity",
  passengerCapacity: "Passenger Capacity",
  vehicleModel: "Vehicle Model",
  brandName: "Brand Name",
  vehicleType: "Vehicle Type",
  vehicleColor: "Vehicle Color",
  specStandard: "Specification Standard",
  declarationNo: "Declaration Number",
  declarationDate: "Declaration Date",
  ownerCode: "Owner Code",
  ownerName: "Owner Name",
  printRemarks: "Print Remarks",
};
const colorMap = {
  red: "#FF0000",
  green: "#53C013",
  blue: "#0000FF",
  yellow: "#cccc00",
  orange: "#FF5500",
  black: "#000000",
  gray: "#808080",
  purple: "#800080",
  pink: "#FF00FF",
  black: "3000000",
  brown: "#A52A2A",
  black: "#000000",
  white: "#FFFFFF",
  gray: "#808080",
  cyan: "#00FFFF",
  magenta: "#FF00FF",
  lime: "#00FF00",
  navy: "#000080",
  maroon: "#800000",
  olive: "#808000",
  teal: "#008080",
  silver: "#C0C0C0",
  gold: "#FFD700",
  // Add more if needed
};
export { colorMap };
export default fields;
